services:

  banrepco-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/api
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head
      && fastapi dev src/main.py --host 0.0.0.0 --port 3000 --reload"
