FROM python:3.13.9-slim

ENV UV_VERSION=0.9.3
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"

# Set working directory
WORKDIR /api

# Create a non-root user
RUN useradd -m -u 1000 appuser

# Install Poetry
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir uv==$UV_VERSION

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --group test

# Copy application code
COPY . /api/

# Change ownership of the app directory to appuser
RUN chown -R appuser:appuser /api

# Switch to non-root user
USER appuser

# Command to run migrations and start the application
CMD ["uv", "run", "pytest", "-v", "--disable-warnings"]
